[build]
  publish = "dist/march/browser"
  command = "    npx nx build march --configuration=production && npx nx run march:server --configuration=production"
+  functions = "./functions"
[[redirects]]
  from = "/*"
  to = "/index.html"[build]
  status = 200
